# Site settings
title: Goodbright Consulting
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://goodbright.nz" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
logo: "/assets/img/goodbright_logo_sq.png"

# User settings
site_description: Miles Thompson on the web
email: utunga @̸̅ͅ gmail.com
github_username:  utunga
insta_username:  utunga216
medium_username: utunga216
repository: utunga/goodbright

sass:
    style: compressed

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
